Drain script should not fail when there is a stale HAProxy pid in pidfile.

diff --git a/jobs/haproxy/templates/drain.erb b/jobs/haproxy/templates/drain.erb
--- a/jobs/haproxy/templates/drain.erb
+++ b/jobs/haproxy/templates/drain.erb
@@ -21,9 +21,16 @@ if [[ ! -f ${pidfile} ]]; then
 fi
 
 pid="$(cat ${pidfile})"
+if ! [ pgrep -F "${pidfile}" ]; then
+  # In case haproxy_wrapper process is stale, pid_exists will be empty,
+  # the drain job should not fail
+  echo "$(date): There was no process for the recorded haproxy_wrapper PID." >> ${logfile}
+  echo 0
+  exit 0
+fi
 
 haproxy_wrapper_pid=$(pgrep -P "$pid" haproxy_wrapper)
-<%- if p('ha_proxy.syslog_server') == "stdout" || p('ha_proxy.syslog_server') == "stderr" -%>
+<%- if p("ha_proxy.syslog_server") == "stdout" || p("ha_proxy.syslog_server") == "stderr" -%>
 haproxy_master_pid=$(pgrep -P "$haproxy_wrapper_pid" -x haproxy)
 <%- else -%>
 haproxy_master_pid=$(pgrep -P "$pid" -x haproxy)
